# Generated by Django 6.0.7 on 2026-07-27 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم المستلم')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('street', models.CharField(max_length=150, verbose_name='الشارع')),
                ('building_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المبنى')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('additional_details', models.TextField(blank=True, verbose_name='تفاصيل إضافية')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
                'ordering': ['-created_at'],
            },
        ),
    ]
